# Generated by Django 5.1.3 on 2024-11-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attributes',
        ),
    ]
