# Generated by Django 5.1.3 on 2024-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0002_remove_card_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
