# Generated by Django 5.1.5 on 2025-01-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='treningpro.user', verbose_name='Пользователь'),
        ),
    ]
