# Generated by Django 5.1.5 on 2025-01-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningpro', '0002_user_role_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
