# Generated by Django 5.1.5 on 2025-01-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoska', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='id_role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='avoska.role', verbose_name='Роль'),
        ),
    ]
