# Generated by Django 5.1.5 on 2025-01-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoska', '0003_alter_user_table_id_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_statuses', to='avoska.status', verbose_name='Статус заказа'),
        ),
    ]
