# Generated by Django 5.1.3 on 2024-11-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_task_date_modified_alter_task_tasklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasklist',
        ),
    ]
