# Generated by Django 5.1.3 on 2024-11-22 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_remove_task_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.tasklist'),
        ),
    ]
