# Generated by Django 5.1.3 on 2025-01-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='id_role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.role', verbose_name='Роль'),
        ),
    ]
