# Generated by Django 5.1.3 on 2024-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karttabl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='detail_page_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='detail_page_url',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='detail_page_url',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='homeappliance',
            name='detail_page_url',
        ),
        migrations.RemoveField(
            model_name='homeappliance',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='detail_page_url',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/karttabl/cars/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/karttabl/clothes/'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/karttabl/electronics/'),
        ),
        migrations.AddField(
            model_name='homeappliance',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/karttabl/home_appliances/'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/karttabl/jewelry/'),
        ),
    ]
