# Generated by Django 5.1.5 on 2025-01-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carforuser', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='carforuser.role'),
        ),
    ]
