# Generated by Django 5.1.5 on 2025-01-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carforuser', '0003_alter_user_id_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
