# Generated by Django 5.1.5 on 2025-01-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_alter_task_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helper.status'),
        ),
    ]
