# Generated by Django 5.1.3 on 2025-01-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='module1_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='module1_user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='CleaningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('service_type', models.CharField(choices=[('general', 'Общий клининг'), ('deep', 'Генеральная уборка'), ('post_construction', 'Послестроительная уборка'), ('carpet', 'Химчистка ковров и мебели')], max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=50)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('completed', 'Услуга оказана'), ('cancelled', 'Услуга отменена')], default='new', max_length=20)),
                ('reason_for_cancellation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
